### ISSUE TITLE
SSR?

### ISSUE THREAD

**Issue by cliqer** [chris-visser/meteor-vue-boilerplate#1]
Any suggestions of how to implement meteor's ssr on this please?

**Comment by chris-visser** [comment]
Just start creating pages in the pages folder and extend the ./src/app/routes.js file with a route for that page. This will render the html on the server and on the client.

It is using Meteor's SSR functionality on the background (using server-render and sink). You can find the code in Akryum's meteor-vue-component package [here](https://github.com/meteor-vue/vue-meteor/blob/ca8a985e8013782274d7fa51698e934a23c61edf/packages/vue-ssr/server/index.js#L72)

**Comment by cliqer** [comment]
Awesome,
Many thanks Chris
