### ISSUE TITLE
About page doesn't show

### ISSUE THREAD

**Issue by jamgold** [chris-visser/meteor-vue-boilerplate#3]
The secondary layout uses a named slot, but the About.vue template doesn't define the slot. So after reading the documentation for Slots, I figured I just add the slot to the template in About.vue, but it still does not display the About.vue content. Can you please suggest how to fix this?

**Comment by chris-visser** [comment]
See above fix. Since the slot on the secondary layout had a name, the page was not automatically assigned. Thanks for reporting :+1:

**Comment by jamgold** [comment]
Thank you. It does raise the question **how** to use named slots, however :)

**Comment by chris-visser** [comment]
Yea indeed. Its actually more a trade-off. Slots are used in a different way. I have a project where I import the layout in each page: 

```
<template>
  <the-page-layout>
    <article-list slot="main" :articles="articles" />

    <the-about-me-block slot="aside" />
    <the-guides-block slot="aside" :guides="guides" />
  </the-page-layout>
</template>

<script>
  import ThePageLayout from '~/components/ThePageLayout';
  import ArticleList from '~/components/ArticleList';
  import TheAboutMeBlock from '~/components/TheAboutMeBlock';
  import TheGuidesBlock from '~/components/TheGuidesBlock';

  export default {
    components: {
      ThePageLayout,
      TheAboutMeBlock,
      TheGuidesBlock,
      ArticleList,
    },
...
```

The layout looks like this (which I love since its only defining the layout):

```
<template>
  <div id="page">
    <header id="page-heading">
      <slot name="heading"></slot>
    </header>

    <main id="page-body">
      <slot name="main"></slot>
    </main>

    <div id="page-aside">
      <slot name="aside"></slot>
    </div>
  </div>
</template>
```
